<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jenis Dokumen_27IN</name>
   <tag></tag>
   <elementGuidId>fad87caf-6693-4e1e-918b-3ef78dd38375</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#27IN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='27IN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f3c9118-fb06-46f4-a870-4984fdef01e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ec666a8c-61eb-4192-849b-32daf40a98fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>27IN</value>
      <webElementGuid>d7cabfe7-07e2-4c05-884d-47d19ad5790d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>27IN</value>
      <webElementGuid>d876b98b-6dbb-4262-a491-a2ee9af442d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;27IN&quot;)</value>
      <webElementGuid>5af3ecaf-1ed3-4947-a2f4-3fc87cca46c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='27IN']</value>
      <webElementGuid>47b83bca-ab78-44be-acbf-27142130c736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div/div/div/div[2]/div/div/form/div[3]/div[2]/label/input</value>
      <webElementGuid>9d421bb0-7c7d-4250-bdac-bf66f360319f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>da22ee7a-f24f-4143-814c-e7d59af28701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = '27IN']</value>
      <webElementGuid>9ad82d0d-ae8e-4740-b929-2a8b80b3f453</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
