<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BPNBPNCGKCGKDPSDPSKNOKNOSUBSUBUPGUPG305_7f9f37</name>
   <tag></tag>
   <elementGuidId>48a1cd4b-3c1f-4319-8aea-08bf1c3f7639</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chart']/div/div[2]/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c759f235-60d8-4bca-87d4-ca3ead8ebfb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-body</value>
      <webElementGuid>27a514f0-8420-4e27-8d3e-bdcd5ae741ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BPNBPNCGKCGKDPSDPSKNOKNOSUBSUBUPGUPG30510547888449456581200120090090060060030030000Download SVGDownload PNGDownload CSV</value>
      <webElementGuid>b9a29c78-3af7-40dd-9c97-3626f43ffd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chart&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;card card-plb&quot;]/div[@class=&quot;card-body&quot;]</value>
      <webElementGuid>9ccdeab4-5e5c-4bc1-b5ed-b3a96bd53e0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chart']/div/div[2]/div[2]/div/div[2]</value>
      <webElementGuid>df842203-2024-4c89-8820-816b26fdaecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo Akhir Allotment'])[1]/following::div[2]</value>
      <webElementGuid>7cb71a6d-36ac-4c44-be80-b69be7dbf141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status BC 28 Tahun 2022'])[1]/following::div[5]</value>
      <webElementGuid>05e8fe88-61fa-41d3-b181-d644c38e9a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]</value>
      <webElementGuid>d6c504d1-b1e2-4e36-b9a9-7dafa45b346b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'BPNBPNCGKCGKDPSDPSKNOKNOSUBSUBUPGUPG30510547888449456581200120090090060060030030000Download SVGDownload PNGDownload CSV' or . = 'BPNBPNCGKCGKDPSDPSKNOKNOSUBSUBUPGUPG30510547888449456581200120090090060060030030000Download SVGDownload PNGDownload CSV')]</value>
      <webElementGuid>ce16042a-5194-4636-a9c1-3aaea4dc6032</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
